name: Build And Push Docker Image To Docker Hub
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build The Docker Image
      run: docker build -t blueclikk/locations-marker:live -f LocationsMarker.API/Dockerfile .
    - name: Push The Image To Docker Hub
      run: |
        docker login -u blueclikk -p ${{ secrets.BLUE_CLICK_HUB_TOKEN }}
        docker push blueclikk/locations-marker:live